onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
# Prevents installation of packages newer than 7 days
# to mitigate supply chain risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@upleveled/*'
  - eslint-config-upleveled
  - stylelint-config-upleveled
  # Renovate security update: next@16.1.5
  - next@16.1.5
# Fail on pnpm ignored build scripts
# - https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true
