name: Lint, Check Types, Cypress Test
on: push

jobs:
  check-types:
    name: Lint, Check Types, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm eslint . --max-warnings 0
      - run: pnpm tsc
      - name: Cache NPM and Cypress 📦
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      # Use Cypress GitHub action to run tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
        run:
          build: pnpm build
          start: pnpm start
